### ISSUE TITLE
AutodiscoverService issue

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#153]
Inside `GetSettings(identities, settings, requestedVersion, getSettingsMethod, getDomainMethod)` I am loggin what happens during the call to `GetSettingsRecursiveLookup()`:

```
// hosts = [ 'autodiscover.mydomain.ch', 'mydomain.ch' ]
// domainName = 'mydomain.ch'
Determining which endpoints are enabled for host autodiscover.ethz.ch
Host returned enabled endpoint flags: Legacy, Soap, WsSecurity
// HERE GetSettingsRecursiveLookup FAILS WITH ERROR
--hard checking for office 365 with node.js http request and presence of header x-federationtrusttokenissueruri: urn:federation:MicrosoftOnline. All other redirection wil fail
...
```
However `GetSettingsRecursiveLookup()` probably fails due to a bug, cause printing out the error:

```
TypeError: Cannot read property 'ToString' of null
    at GetUserSettingsRequest.AutodiscoverRequest.WriteSoapRequest (/home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Autodiscover/Requests/AutodiscoverRequest.js:345:124)
    at GetUserSettingsRequest.AutodiscoverRequest.InternalExecute (/home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Autodiscover/Requests/AutodiscoverRequest.js:83:14)
    at GetUserSettingsRequest.Execute (/home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Autodiscover/Requests/GetUserSettingsRequest.js:27:21)
    at AutodiscoverService.InternalGetUserSettings (/home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Autodiscover/AutodiscoverService.js:519:24)
    at /home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Autodiscover/AutodiscoverService.js:351:24

```

**Comment by gautamsi** [comment]
how are you calling this method?

**Comment by marcoancona** [comment]
Similarly to the example code...

```
let autod = new ews.AutodiscoverService();
	autod.Credentials = new ews.ExchangeCredentials(params.login, pass);
	autod.TraceEnabled = true;
	let settings = [
		ews.UserSettingName.InternalEwsUrl,
		ews.UserSettingName.ExternalEwsUrl,
		ews.UserSettingName.UserDisplayName,
		ews.UserSettingName.UserDN,
		ews.UserSettingName.EwsPartnerUrl,
		ews.UserSettingName.DocumentSharingLocations,
		ews.UserSettingName.MailboxDN,
		ews.UserSettingName.ActiveDirectoryServer,
		ews.UserSettingName.CasVersion,
		ews.UserSettingName.ExternalWebClientUrls,
		ews.UserSettingName.ExternalImap4Connections,
		ews.UserSettingName.AlternateMailboxes
	];

	autod.GetUsersSettings([params.email], settings)
		.then(
			(response) => {
				console.log(`Response: ${response}`); // response undefined
                 ...
                );
```

 I was trying to find out why response is undefined and first I found that it only detects Legacy mode due to #152. Once fixed that I get this log:

```
Determining which endpoints are enabled for host autodiscover.ethz.ch
Host returned enabled endpoint flags: Legacy, Soap, WsSecurity
--hard checking for office 365 with node.js http request and presence of header x-federationtrusttokenissueruri: urn:federation:MicrosoftOnline. All other redirection wil fail
Trying to get Autodiscover redirection URL from http://autodiscover.ethz.ch/autodiscover/autodiscover.xml.
--Request error: 403, undefined
Response: undefined
```

However, that error 403 happens while trying to access office 365 apis. And this, on the other hand, is due to the exception mentioned above which is treated as failed request.

**Comment by gautamsi** [comment]
autodiscover is re-written #324, try latest dev build using `@next` tag on npm.
