### ISSUE TITLE
Exception.js does not handle Circular references

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#167]
Sometimes trying to print an exception raises another exception:
```
Unhandled rejection TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ServiceResponseException.Exception.toString (/home/node_modules/ews-javascript-api/js/Exceptions/Exception.js:42:21)
    at StringPrettyPrinter.PrettyPrinter.format (/home/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1768:31)

```

Using [json3](https://www.npmjs.com/package/json3) might be the easiest way to workaround this.

**Comment by gautamsi** [comment]
I will fix this later, meanwhile you can fix by modifying toString method to return stack property rather than performing json.stringify
