### ISSUE TITLE
Error 401 

### ISSUE THREAD

**Issue by SHAHRUKH-KHAN** [gautamsi/ews-javascript-api#183]
I am using the ntlmXHR provided by you.

```
var PromiseFactory = require("ews-javascript-api").PromiseFactory;
var httpntlm = require('httpntlm');
var ntlmXHRApi = (function () {
    function ntlmXHRApi(user, password) {
        this.userName = user;
        this.password = password;
    }
    ntlmXHRApi.prototype.xhr = function (xhroptions) {
        var _this = this;
        var userName = _this.userName;
        var domain = '';
        if (userName.indexOf("\\") >= 0) {
            var usersplit = userName.split("\\", 2);
            userName = usersplit[1];
            domain = usersplit[0];
        }
        var headers = xhroptions.headers;

        if (headers["Authorization"]) {
            delete headers["Authorization"];
        }
        var xhr = {
            url: xhroptions.url,
            username: userName,
            password: _this.password,
            workstation: '',
            domain: domain,
            body: xhroptions.data,
            headers: headers
        }
        // no need to use PromiseFactory.create, just return Q promise in your implementation. 
        return PromiseFactory.create(function (successDelegate, errorDelegate, progressDelegate) {
            httpntlm.post(xhr, function (err, res) {
                res.getAllResponseHeaders = function () {
                    var header = "";
                    if (res.headers) {
                        for (var key in res.headers) {
                            header += key + " : " + res.headers[key] + "\r\n";
                        }
                    }
                    return header;
                }
                if (err) {
                    errorDelegate(err);
                }
                else {
                    //mapping properties to expected return properties.
                    res['responseText'] = res.body;
                    res['status'] = res.statusCode;
                    if (res.statusCode === 200) {
                        successDelegate(res);
                    }
                    else {
                        errorDelegate(res);
                    }
                }
            });
        });
    };
    Object.defineProperty(ntlmXHRApi.prototype, "type", {
        get: function () {
            return "ntlmXHR";
        },
        enumerable: true,
        configurable: true
    });
    return ntlmXHRApi;
})();
exports.ntlmXHRApi = ntlmXHRApi;
```

**Below is in my index.js**
```
function sendEmail(data) {
    var ntlmXHRApo = new ntlmXHR.ntlmXHRApi("abd@co.in", "pass");
    //create ExchangeService object
    var autod = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
    //set ews endpoint url to use
    autod.XHRApi = ntlmXHRApo;
    autod.Credentials = new ews.ExchangeCredentials("abd@co.in", "pass");
    autod.Url = new ews.Uri("....Exchange.asmx");

    var msgattach = new ews.EmailMessage(autod);
    msgattach.Subject = "SPAMING";
    msgattach.Body = new ews.MessageBody("Testing");
    msgattach.ToRecipients.Add("abc@co.in");
    /** AddFileAttachment parameters - 
     * filename (name of attachment as shown in outlook/owa not actual file from disk), 
     * base64 content of file (read file from disk and convert to base64 yourself)
     */
    //msgattach.Attachments.AddFileAttachment("ratext.txt", data.toString('base64'));
    /*msgattach.SendAndSaveCopy().then(() => {
        console.log("------------");
    }, (ei) => {
        console.log(ei.stack, ei.stack.split("\n"));
        console.log("------------");
    });*/
   msgattach.Send().then(()=>console.log('hi'))
}
```

Below is the error, I get 
I have changed the URL and soap data, rest is as it is.
```
[ComplexProperty.Changed] OnChange events not fired due to circular calling, tod
o: fix needed
sending ews request
{ url: '....Exchange.asmx',
  headers:
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     Authorization: 'Basic c2hhaHJ1a2gua2hhbkBhY2NlbnR1cmUuY29tOjc4NkBzd3NkTUJB'
 },
  type: 'POST',
  data: '<soap:Envelope>..XML data...</soap:Envelope>'
}
Error in calling service, error code:401
server : Microsoft-IIS/8.0
request-id : 12db94d6-7092-4e0f-91b0-98e2a8de887a
www-authenticate : Negotiate, NTLM
x-powered-by : ASP.NET
x-feserver : BLUPR42CA013
date : Thu, 18 May 2017 09:39:57 GMT
connection : close
content-length : 0
```

The url in my above error is the one which I get after running the `testEmailAuto-configuration` from my outlook icon in my desktop tray and picking it from `Availability Service URL`

I checked my outlook .. it is having NTLM authentication .

How can I fix this... ?

**Comment by gautamsi** [comment]
if it is NTLM v2, this adapter will not work. take a look at npm module `ews-javascript-api-auth' NTLM v2 is supported there. readme has how to get started (use ews-javascript-api@next from npm for this)

**Comment by SHAHRUKH-KHAN** [comment]
How to get version 0.9?

**Comment by gautamsi** [comment]
`npm install ews-javascript-api@next`

**Comment by SHAHRUKH-KHAN** [comment]
Code I changed in my function
```
ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi("username", "pass"));
    var autod = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);    
    autod.Credentials = new ews.ExchangeCredentials("username", "pass");
    autod.Url = new ews.Uri("https://.../EWS/Exchange.asmx");

var msgattach = new ews.EmailMessage(autod);
    msgattach.Subject = "SPAMING";
    msgattach.Body = new ews.MessageBody("Testing");

msgattach.Send().then(()=>console.log('send'));
```

Error I got
```
Error in calling service, error code:401
server : Microsoft-IIS/8.0
request-id : e01a42af-61b7-454f-9c2d-16db55cfdf65
www-authenticate : Negotiate, NTLM
x-powered-by : ASP.NET
x-feserver : CO2PR42CA022
date : Fri, 19 May 2017 05:30:51 GMT
connection : close
content-length : 0

Unhandled rejection Exception
    at CreateItemRequest.ServiceRequestBase.ProcessWebException (C:\Users\shahru
kh.khan\Desktop\Tricks\ratext\node_modules\ews-javascript-api\js\Core\Requests\S
erviceRequestBase.js:270:36)
    at C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_modules\ews-javascript-
api\js\Core\Requests\SimpleServiceRequestBase.js:64:41
    at tryCatcher (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_modules\blu
ebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shahrukh.khan\Desktop\Tricks\
ratext\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node
_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\nod
e_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\nod
e_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_modu
les\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_mod
ules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\shahrukh.khan\Desktop\Tricks\ratext
\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Any suggestions...

**Comment by gautamsi** [comment]
are you using username along with domain name as well? if not there may be issue.

**Comment by SHAHRUKH-KHAN** [comment]
I used shahrukh.khan@mydomain.com as my username.

**Comment by SHAHRUKH-KHAN** [comment]
Should I make any changes in Outlook also. I am in my office network

**Comment by gautamsi** [comment]
is that upn or email address, if the userPrincipalname (example skhan@domain.com where skhan is the login id - samaccountname) is different than email address, you will see 401.

**Comment by SHAHRUKH-KHAN** [comment]
I wrote it as below
```
var autod = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
    //set ews endpoint url to use
    autod.XHRApi = new ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi("shahrukh.khan@abcd.com", "pass"));
    autod.Credentials = new ews.ExchangeCredentials("shahrukh.khan@abcd.com", "pass");
    autod.Url = new ews.Uri("https://email.o365.abcd.com/EWS/Exchange.asmx");

var msgattach = new ews.EmailMessage(autod);
    msgattach.Subject = "SPAMING";
    msgattach.Body = new ews.MessageBody("Testing");

msgattach.Send().then(()=>console.log('send'));
```

If this is not correct - 
I use this email address(shahrukh.khan@abcd.com) to login in my outlook.

**Comment by gautamsi** [comment]
looks like you want to do this

```js
var ews = require("ews-javascript-api");
var ewsAuth = require("ews-javascript-api-auth");
ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi(credentials.userName, credentials.password));
```

`autod.XHRApi` is not the right ways for 0.9, use `ews.ConfigurationApi.ConfigureXHR` function

**Comment by SHAHRUKH-KHAN** [comment]
Ok! I did that. 
Good news - XML is created
Bad - Exception is thrown

```
{ url: 'https://email.o365.abcd.com/EWS/Exchange.asmx',
  headers:
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     Authorization: 'Basic c2hhaHJ1a2gua2hhbkBhY2NlbnR1cmUuY29tOjc4NkBzd3NkTUJB'
 },
  type: 'POST',
  data: '<soap bla blah>' }
Error in calling service, error code:401
server : Microsoft-IIS/8.0
request-id : cd04c421-f77b-44f0-a70c-f8a1ed64cf93
www-authenticate : Negotiate, NTLM
x-powered-by : ASP.NET
x-feserver : DM2PR42CA011
date : Fri, 19 May 2017 11:48:43 GMT
connection : close
content-length : 0

Unhandled rejection Exception
    at CreateItemRequest.ServiceRequestBase.ProcessWebException (C:\Users\shahru
kh.khan\Desktop\Tricks\ratext\node_modules\ews-javascript-api\js\Core\Requests\S
erviceRequestBase.js:270:36)
    at C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_modules\ews-javascript-
api\js\Core\Requests\SimpleServiceRequestBase.js:64:41
    at tryCatcher (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_modules\blu
ebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shahrukh.khan\Desktop\Tricks\
ratext\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node
_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\nod
e_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\nod
e_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_modu
les\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\shahrukh.khan\Desktop\Tricks\ratext\node_mod
ules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\shahrukh.khan\Desktop\Tricks\ratext
\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by gautamsi** [comment]
you may want to setup a shared session to work it out. send email (from my github profile) or use gitter 1:1 chat to set this up.

**Comment by SHAHRUKH-KHAN** [comment]
Sure. thanks :) 
On Gitter

**Comment by SHAHRUKH-KHAN** [comment]
Closing, as it was just a version update issue.
