### ISSUE TITLE
Timezone offset handling error causes error parsing loaded message

### ISSUE THREAD

**Issue by erduende** [gautamsi/ews-javascript-api#198]
When a message date field has offset like 2017-08-25T14:03:41+02:00 the method ExchangeServiceBase.prototype.ConvertUniversalDateTimeStringToLocalDateTime adds 'Z' causing an invalid date format.

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2017-08-25T14:03:41+02:00Z, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:320:94)
    at configFromString (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:2178:11)
    at configFromInput (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:2547:9)
    at prepareConfig (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:2530:9)
    at createFromConfig (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:2497:40)
    at createLocalOrUTC (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:2584:12)
    at createLocal (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:2588:12)
    at hooks (/home/developer/Projects/components/email-client/node_modules/moment/moment.js:16:25)
    at Function.DateTime.Parse (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/DateTime.js:158:21)
    at ExchangeServiceBase.ConvertUniversalDateTimeStringToLocalDateTime (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/ExchangeServiceBase.js:147:48)
    at DateTimePropertyDefinition.LoadPropertyValueFromXmlJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/PropertyDefinitions/DateTimePropertyDefinition.js:85:33)
    at PropertyBag.LoadFromXmlJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/PropertyBag.js:398:53)
    at EmailMessage.ServiceObject.LoadFromXmlJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/ServiceObjects/ServiceObject.js:240:26)
    at Function.EwsServiceJsonReader.ReadServiceObjectsCollectionFromJson (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/EwsServiceJsonReader.js:48:39)
    at GetItemResponse.ReadElementsFromXmlJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Responses/GetItemResponse.js:47:65)
    at GetItemResponse.ServiceResponse.LoadFromXmlJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Responses/ServiceResponse.js:145:22)
    at GetItemRequestForLoad.MultiResponseServiceRequest.ParseResponseXMLJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:87:22)
    at GetItemRequestForLoad.MultiResponseServiceRequest.ParseResponse (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:133:25)
    at GetItemRequestForLoad.ServiceRequestBase.ReadResponseXmlJsObject (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:323:32)
    at GetItemRequestForLoad.SimpleServiceRequestBase.ReadResponsePrivate (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:105:44)
    at /home/developer/Projects/components/email-client/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:59:49
    at tryCatcher (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/developer/Projects/components/email-client/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by gautamsi** [comment]
can you give me more context, what exactly your request to server was and possibly the response xml.

**Comment by erduende** [comment]
Sure, I have discovered that it only fails when MimeContent is requested, in such case date format has time offset suffix which casuses the bug when 'Z' is added to datetime string in ExchangeServiceBase.prototype.ConvertUniversalDateTimeStringToLocalDateTime method.

**Request with MimeContent property**
```javascript
this.itemProperties = new this.ews.PropertySet(this.ews.BasePropertySet.FirstClassProperties, [
    this.ews.EmailMessageSchema.MimeContent,
    this.ews.EmailMessageSchema.TextBody,
]);
```
Response fragment
```xml
...
<t:DateTimeSent>2017-08-02T11:43:12+02:00</t:DateTimeSent>
<t:DateTimeCreated>2017-08-02T11:43:18+02:00</t:DateTimeCreated>
<t:ResponseObjects>
  <t:ReplyToItem/>
  <t:ReplyAllToItem/>
  <t:ForwardItem/>
</t:ResponseObjects>
...
```

**Request without MimeContent property**
```javascript
this.itemProperties = new this.ews.PropertySet(this.ews.BasePropertySet.FirstClassProperties, [
    this.ews.EmailMessageSchema.TextBody,
]);
```
Response fragment
```xml
...
<t:DateTimeSent>2017-08-02T09:43:12Z</t:DateTimeSent>
<t:DateTimeCreated>2017-08-02T09:43:18Z</t:DateTimeCreated>
<t:ResponseObjects>
  <t:ReplyToItem/>
  <t:ReplyAllToItem/>
  <t:ForwardItem/>
</t:ResponseObjects>
...
```

I hope it helps solving the bug. 
Thx

**Comment by gautamsi** [comment]
i am trying to fix this by changing comparison to 

```js
if (value.toLowerCase().indexOf("z") < 0 && ["+", "-"].indexOf(value.substr(19, 1)) < 0) {
    value += "Z";
}
```
