### ISSUE TITLE
Changing TimeZones issue

### ISSUE THREAD

**Issue by baloo887** [gautamsi/ews-javascript-api#209]
Hi,
If I try to change the timezone of a new appointment I get the following error:

`[31mUnhandled rejection Exception: Invalid date and time: Thu Oct 12 2017 13:30:00 GMT+0200.
    at ScopedDateTimePropertyDefinition.ScopeToTimeZone (node_modules/ews-javascript-api/js/PropertyDefinitions/ScopedDateTimePropertyDefinition.js:85:27)
    at ScopedDateTimePropertyDefinition.DateTimePropertyDefinition.GetConvertedDateTime (node_modules/ews-javascript-api/js/PropertyDefinitions/DateTimePropertyDefinition.js:67:38)
    at ScopedDateTimePropertyDefinition.DateTimePropertyDefinition.WritePropertyValueToXml (node_modules/ews-javascript-api/js/PropertyDefinitions/DateTimePropertyDefinition.js:119:42)
    at PropertyBag.WriteToXml (node_modules/ews-javascript-api/js/Core/PropertyBag.js:577:40)
    at Appointment.ServiceObject.WriteToXml (node_modules/ews-javascript-api/js/Core/ServiceObjects/ServiceObject.js:317:79)
    at CreateItemRequest.CreateRequest.WriteElementsToXml (node_modules/ews-javascript-api/js/Core/Requests/CreateRequest.js:64:17)
    at CreateItemRequest.ServiceRequestBase.WriteBodyToXml (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:460:14)
    at CreateItemRequest.ServiceRequestBase.WriteToXml (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:529:14)
    at CreateItemRequest.ServiceRequestBase.EmitRequest (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:165:18)
    at CreateItemRequest.ServiceRequestBase.BuildXHR (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:131:14)
    at node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:48:33
    at Promise._execute (node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (node_modules/bluebird/js/release/promise.js:79:10)
    at CreateItemRequest.SimpleServiceRequestBase.InternalExecute (node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:47:16)
    at node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:45:19
    at Promise._execute (node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (node_modules/bluebird/js/release/promise.js:79:10)
    at CreateItemRequest.MultiResponseServiceRequest.Execute (node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:44:16)
    at ExchangeService.InternalCreateItems (node_modules/ews-javascript-api/js/Core/ExchangeService.js:690:24)
    at ExchangeService.CreateItem (node_modules/ews-javascript-api/js/Core/ExchangeService.js:484:21)[0m`

Here is my code:

`const intTimeZone = _ewsJavascriptApi.TimeZoneInfo.FindSystemTimeZoneById("UTC");
    var date = new _ewsJavascriptApi.DateTime(evtdatetime);

    var selfinclude = includeme; // avoid modification of a parameter value

    if (selfinclude == null) {
      console.log('selfinclude of the event was undefined. Now setted as true');
      selfinclude = true;
    }
    var timewindow = new _ewsJavascriptApi.TimeWindow(date, date.AddMinutes(minduration));

    var meeting = new _ewsJavascriptApi.Appointment(exch);

    meeting.Subject = subject;
    meeting.Body = new _ewsJavascriptApi.MessageBody(body);
    meeting.Start = timewindow.StartTime;
    meeting.End = timewindow.EndTime;
    meeting.StartTimeZone = intTimeZone;
    meeting.EndTimeZone = intTimeZone;
    if (location) {
      meeting.Location = location;
    }
    if (selfinclude) {
      meeting.RequiredAttendees.Add(exch.Credentials.UserName);
    }
    if (reqattendees) {
      reqattendees.forEach(function (person) {
        meeting.RequiredAttendees.Add(person);
      });
    }

    meeting.Save(_ewsJavascriptApi.SendInvitationsMode.SendToAllAndSaveCopy);`

I get the same error if i try to specify the timezone  in the exch constructor:

`new _ewsJavascriptApi.ExchangeService(_ewsJavascriptApi.ExchangeVersion.Exchange2013,  _ewsJavascriptApi.TimeZoneInfo.FindSystemTimeZoneById('UTC'));`

There's something wrong in my code?
Thanks for the support

**Comment by gautamsi** [comment]
have you tried `_ewsJavascriptApi.TimeZoneInfo.Utc` for utc timezone?

**Comment by gautamsi** [comment]
by default `ews-javascript-api` uses local time zone, you can create UTC scoped service `new _ewsJavascriptApi.ExchangeService(_ewsJavascriptApi.ExchangeVersion.Exchange2013, _ewsJavascriptApi.TimeZoneInfo.Utc);`

**Comment by baloo887** [comment]
Hi thanks for the reply.  
Yes I've tried also with _ewsJavascriptApi.TimeZoneInfo.Utc and I still get the same error.

**Comment by baloo887** [comment]
More over, If i don't specify any TimeZone but I set the process.env.TZ to "UTC" I get another error:

`Unhandled rejection Error: value can not be of type object
    at EwsServiceXmlWriter.ConvertObjectToString (node_modules/ews-javascript-api/js/Core/EwsServiceXmlWriter.js:113:35)
    at EwsServiceXmlWriter.WriteAttributeValue (node_modules/ews-javascript-api/js/Core/EwsServiceXmlWriter.js:174:32)
    at TimeZoneDefinition.WriteAttributesToXml (node_modules/ews-javascript-api/js/ComplexProperties/TimeZones/TimeZoneDefinition.js:339:20)
    at TimeZoneDefinition.ComplexProperty.WriteToXml (node_modules/ews-javascript-api/js/ComplexProperties/ComplexProperty.js:108:14)
    at TimeZoneDefinition.WriteToXml (node_modules/ews-javascript-api/js/ComplexProperties/TimeZones/TimeZoneDefinition.js:383:37)
    at CreateItemRequest.ServiceRequestBase.WriteToXml (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:498:45)
    at CreateItemRequest.ServiceRequestBase.EmitRequest (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:165:18)
    at CreateItemRequest.ServiceRequestBase.BuildXHR (node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:131:14)
    at node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:48:33
    at Promise._execute (node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (node_modules/bluebird/js/release/promise.js:79:10)
    at CreateItemRequest.SimpleServiceRequestBase.InternalExecute (node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:47:16)
    at node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:45:19
    at Promise._execute (node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (node_modules/bluebird/js/release/promise.js:79:10)
    at CreateItemRequest.MultiResponseServiceRequest.Execute (node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:44:16)
    at ExchangeService.InternalCreateItems (node_modules/ews-javascript-api/js/Core/ExchangeService.js:690:24)
    at ExchangeService.CreateItem (node_modules/ews-javascript-api/js/Core/ExchangeService.js:484:21)
    at Appointment.Item.InternalCreate (node_modules/ews-javascript-api/js/Core/ServiceObjects/Items/Item.js:826:33)
    at Appointment.Save (node_modules/ews-javascript-api/js/Core/ServiceObjects/Items/Appointment.js:810:25)[0m` 

I'm using node 8.4.0 on macOs10.12.6

Could this be related to the UTC time zone?

**Comment by gautamsi** [comment]
I testes in windows with no issues, will try in mac later. 
where do you get the date object? 

I tried like this

```js
timewindow = new _ewsJavascriptApi.TimeWindow(_ewsJavascriptApi.DateTime.Now.AddHours(4), _ewsJavascriptApi.DateTime.Now.AddHours(5));
meeting = new _ewsJavascriptApi.Appointment(service);
meeting.Subject = "subject";
meeting.Body = new _ewsJavascriptApi.MessageBody("body");
meeting.Start = timewindow.StartTime;
meeting.End = timewindow.EndTime;
meeting.StartTimeZone = _ewsJavascriptApi.TimeZoneInfo.Utc;
meeting.EndTimeZone = _ewsJavascriptApi.TimeZoneInfo.Utc;
meeting.Location = "location";
meeting.RequiredAttendees.Add("xxxx@xxxxx.com");
meeting.RequiredAttendees.Add("yyyyyy@xxxxx.com");
meeting.Save(_ewsJavascriptApi.SendInvitationsMode.SendToAllAndSaveCopy);```

**Comment by gautamsi** [comment]
I see the issue, I have updates code in my dev machine where it is working fine. on my mac it did get me the error. for time being, you can replace line 28-82 (between `function DateTime(msOrDateOrMomentOrYear, monthOrKind, day, hour, minute, second, millisecond, kind) {` and its closing `}`) while I take some time to push code update.

```js
if (kind === void 0) { kind = DateTimeKind.Unspecified; }
this.kind = DateTimeKind.Unspecified;
this.originalDateInput = null;
var argsLength = arguments.length;
var momentdate = moment();
this.kind = kind;
if (argsLength === 1) {
    if (msOrDateOrMomentOrYear instanceof DateTime) {
        momentdate = msOrDateOrMomentOrYear.MomentDate.clone();
        this.kind = msOrDateOrMomentOrYear.kind;
    }
    else {
        momentdate = moment(msOrDateOrMomentOrYear);
        this.originalDateInput = msOrDateOrMomentOrYear;
    }
}
else if (argsLength === 2) {
    if (monthOrKind === DateTimeKind.Utc && !(msOrDateOrMomentOrYear instanceof moment)) {
        momentdate = moment.utc(msOrDateOrMomentOrYear);
    }
    else {
        momentdate = moment(msOrDateOrMomentOrYear);
    }
    this.kind = monthOrKind;
    if (this.kind === DateTimeKind.Unspecified && !(msOrDateOrMomentOrYear instanceof moment)) {
        this.originalDateInput = msOrDateOrMomentOrYear;
    }
}
else {
    var momentInput = {};
    if (argsLength >= 3) {
        momentInput.year = msOrDateOrMomentOrYear;
        momentInput.month = monthOrKind - 1;
        momentInput.day = day;
    }
    if (argsLength >= 6) {
        momentInput.hour = hour;
        momentInput.minute = minute;
        momentInput.second = second;
    }
    if (argsLength >= 7) {
        momentInput.millisecond = millisecond;
    }
    momentdate = moment(momentInput);
}
if (momentdate && !momentdate.isValid()) {
    var invalid = momentdate.invalidAt();
    throw new ArgumentException_1.ArgumentOutOfRangeException(momentValidity[invalid], invalidDateTimeMessage[momentValidity[invalid]]);
}
this.getMomentDate = function () { return momentdate; };
this.setMomentDate = function (value) { return momentdate = value; };
```

**Comment by baloo887** [comment]
Thanks for the quick fix!

**Comment by zmathew** [comment]
👍  I'm also interested in this as I'm having the same issue. The above fix works when manually applied

**Comment by thomaskrantz** [comment]
Me too. Works when manually applied. Could we have this fix pushed to the npm repository?

**Comment by gautamsi** [comment]
finally it is pushed to 0.9.2. please reopen if still have issue.
