### ISSUE TITLE
CreateItems not working with Appointments

### ISSUE THREAD

**Issue by baloo887** [gautamsi/ews-javascript-api#210]
Hi,
I'm trying to create a list of appointments with the CreateItems method, but i get the following error:

`calendar service : TypeError: this.ParentFolderId.WriteToXml is not a function
    at CreateItemRequest.CreateRequest.WriteElementsToXml (/node_modules/ews-javascript-api/js/Core/Requests/CreateRequest.js:58:33)
    at CreateItemRequest.ServiceRequestBase.WriteBodyToXml (/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:460:14)
    at CreateItemRequest.ServiceRequestBase.WriteToXml (/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:529:14)
    at CreateItemRequest.ServiceRequestBase.EmitRequest (/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:165:18)
    at CreateItemRequest.ServiceRequestBase.BuildXHR (/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:131:14)
    at /node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:48:33
    at Promise._execute (/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/node_modules/bluebird/js/release/promise.js:79:10)
    at CreateItemRequest.SimpleServiceRequestBase.InternalExecute (/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:47:16)
    at /node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:45:19
    at Promise._execute (/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/node_modules/bluebird/js/release/promise.js:79:10)
    at CreateItemRequest.MultiResponseServiceRequest.Execute (/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:44:16)
    at ExchangeService.InternalCreateItems (/node_modules/ews-javascript-api/js/Core/ExchangeService.js:690:24)
    at ExchangeService.CreateItems (/node_modules/ews-javascript-api/js/Core/ExchangeService.js:504:21)
    at /node_modules/dist/modules/createMeeting.js:43:10
    at Promise (<anonymous>)
    at bulkCreateMeeting (/node_modules/dist/modules/createMeeting.js:37:10)
    at Promise (:1310:111)
    at Promise (<anonymous>)`

I'm on osx 10.12 and my code is:

`exch.CreateItems(newMeetings,
      ews.WellKnownFolderName.Calendar,
      ews.MessageDisposition.SendAndSaveCopy,
      ews.SendInvitationsMode.SendToAllAndSaveCopy)`

were newMeetings is an array of Appointment objs created with:

`const date = new ews.DateTime(evtdatetime); // evtdatetime is a moment date obj

  let selfinclude = true;

  const timewindow = new ews.TimeWindow(date, date.AddMinutes(30));

  const meeting = new ews.Appointment(exch);

  meeting.Subject = 'test';
  meeting.Body = new ews.MessageBody('test');
  meeting.Start = timewindow.StartTime;
  meeting.End = timewindow.EndTime;`

Is there something wrong with my code?
thanks
Luca

**Comment by gautamsi** [comment]
[`CreateItems`](https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.exchangeservice.createitems(v=exchg.80).aspx) does not have overload which accepts `WellKnownFolderName` enumeration. you should use like this:

```js
exch.CreateItems(newMeetings, new ews.FolderId(ews.WellKnownFolderName.Calendar), ews.MessageDisposition.SendAndSaveCopy, ews.SendInvitationsMode.SendToAllAndSaveCopy)
```
