### ISSUE TITLE
AutodiscoverUrl undefined

### ISSUE THREAD

**Issue by daychopan** [gautamsi/ews-javascript-api#216]
Using this code:

```
//import ews module
var ews = require('ews-javascript-api');
//create AutodiscoverService object
var autod = new ews.AutodiscoverService(new ews.Uri("https://autodiscover-s.outlook.com/autodiscover/autodiscover.svc"), ews.ExchangeVersion.Exchange2010);

autod.RedirectionUrlValidationCallback = function (url){
//validate if redirection is valid and not malicious, you can also just check for https:// 
// url parameter is a string. 
if(valid(url)){
    return true;
}
    return false;
}
//you can omit url and it will autodiscover the url, version helps throw error on client side for unsupported operations.example - //var autod = new ews.AutodiscoverService(ews.ExchangeVersion.Exchange2010);
//set credential for service
autod.Credentials = new ews.ExchangeCredentials("username", "password");
//create array to include list of desired settings
var settings = [
ews.UserSettingName.InternalEwsUrl,
ews.UserSettingName.ExternalEwsUrl,
ews.UserSettingName.UserDisplayName,
ews.UserSettingName.UserDN,
ews.UserSettingName.EwsPartnerUrl,
ews.UserSettingName.DocumentSharingLocations,
ews.UserSettingName.MailboxDN,
ews.UserSettingName.ActiveDirectoryServer,
ews.UserSettingName.CasVersion,
ews.UserSettingName.ExternalWebClientUrls,
ews.UserSettingName.ExternalImap4Connections,
ews.UserSettingName.AlternateMailboxes
];
//get the setting
autod.GetUserSettings(["email"], settings)
.then(function (response) {
    //do what you want with user settings    
    var tabcount = 0;
    var tabs = function () { return ews.StringHelper.Repeat("\t", tabcount); };
    console.log(autod.Url.ToString());
	//uncoment next line to see full response from autodiscover, you will need to add var util = require('util');
	//console.log(util.inspect(response, { showHidden: false, depth: null, colors: true }));
    for (var _i = 0, _a = response.Responses; _i < _a.length; _i++) {
        var resp = _a[_i];
        console.log(ews.StringHelper.Format("{0}settings for email: {1}", tabs(), resp.SmtpAddress));
        tabcount++;
        for (var setting in resp.Settings) {
            console.log(ews.StringHelper.Format("{0}{1} = {2}", tabs(), ews.UserSettingName[setting], resp.Settings[setting]));
        }
        tabcount--;
    }
}, function (e) {
    //log errors or do something with errors
});
```

Gives me this error:

```
Unhandled rejection TypeError: Cannot read property 'Responses' of undefined
    at C:\Users\jasim\Desktop\RoomUiO\index.js:43:35
    at tryCatcher (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\jasim\Desktop\RoomUiO\node_modules\ews-javascript-api\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

Double checked username, password and email. All are correct, and working on the ews-java-api

**Comment by gautamsi** [comment]
autodiscover is broken for now. needs complete rewrite. not able to find much time these days. might look up over year end holiday.

**Comment by gautamsi** [comment]
autodiscover is re-written, please try the latest dev build using `npm install ews-javascript-api@next`, it will be published with `0.10` version.

**Comment by marcoancona** [comment]
I can confirm that Autodiscover seems to work for me on `ews-javascript-api@next` (0.9.7-dev.1). On the other hand, using this version, other requests seem to fail because the `Authorization`  is not added to the request header. But I guess this is because this version is not finalized yet, isn't it? looking forward to 0.10.0

**Comment by gautamsi** [comment]
In my testing it was working fine. Without the `Authorization` header it would not work anyways

**Comment by gautamsi** [comment]
`Authorization` is not added in several of the Autodiscover calls to prevent leak of credential to rouge hosts. once they appear to be working, then only credentials are sent.

**Comment by marcoancona** [comment]
Sorry, what I mean is that there seems to be a problem with  `Authorization` of requests from `ServiceRequestBase`

For example, I get 401 for the following request. I am not sure what is causing this (username and password are correct, if I POST manually, adding the Authorization, the request works)
```
sending ews request
[16:10:47] { url: 'https://outlook.office365.com/EWS/Exchange.asmx',
  headers:
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml' },
  type: 'POST',
  data:
   '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>AllProperties</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:PermissionSet"></t:FieldURI></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="calendar"><t:Mailbox><t:EmailAddress>ancona.marco@outlook.com</t:EmailAddress></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>' }
```

**Comment by marcoancona** [comment]
Just an idea, but [this line](https://github.com/gautamsi/ews-javascript-api/blob/e6529ba1643018d4a367d8aa68d45afe5e370276/src/js/Core/ExchangeServiceBase.ts#L727) supposed to be commented out? I cannot trace where credentials are set for Basic auth.

**Comment by marcoancona** [comment]
@gautamsi can you please comment on this last issue? I am trying to understand if I am doing something wrong while settings the credentials of if it is an actual problem with the latest version. Thanks.

**Comment by gautamsi** [comment]
should be fixed now, use latest dev build with `ews-javascript-api@next`
