### ISSUE TITLE
Error causes disconnect

### ISSUE THREAD

**Issue by hgezim** [gautamsi/ews-javascript-api#231]
After the connection is opened, either at timeout or before, we get an error:

Code:
```
    private onDisconnect(args: ews.SubscriptionErrorEventArgs) {
        winston.error('[exchange] subscription error ', args.Exception);
        this.connection.Open()
    }
```

Error:
```
[xmldom error]	element parse error: Error: attribute equal must after attrName
@#[line:1,col:508]
error: [exchange] subscription expired with: TypeError: Cannot read property 'ResponseMessages' of undefined
    at GetStreamingEventsRequest.ParseResponse (/Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/ews-javascript-api/js/Core/Requests/GetStreamingEventsRequest.js:73:40)
    at GetStreamingEventsRequest.ServiceRequestBase.ReadResponseXmlJsObject (/Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:323:32)
    at GetStreamingEventsRequest.HangingServiceRequestBase.ParseResponses (/Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:193:39)
    at /Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:102:39
    at FetchStream.<anonymous> (/Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/ews-javascript-api/js/XHRDefaults.js:73:17)
    at FetchStream.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at FetchStream.Readable.push (_stream_readable.js:209:10)
    at FetchStream.drainBuffer (/Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/fetch/lib/fetch.js:84:14)
    at FetchStream.<anonymous> (/Users/gezimhome/projects/clients/TestFireLabs/hendrix-core/node_modules/fetch/lib/fetch.js:326:22)
    at IncomingMessage.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at IncomingMessage.Readable.push (_stream_readable.js:209:10)
    at HTTPParser.parserOnBody (_http_common.js:139:22)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onread (net.js:608:20)
```

**Comment by gautamsi** [comment]
can you grab the soap xml ( set `EwsLogging.DebugLogEnabled = true`) where it breaks?
