### ISSUE TITLE
Ionic 3 Error

### ISSUE THREAD

**Issue by iot-dev01** [gautamsi/ews-javascript-api#240]
Hey,

I try to implement the ews-javascript-api-browser in Ionic 3 app.
After running `ionic start myApp blank` to get a new project and `npm install ews-js-api-browser`, `npm install -g typescript`, `npm run build` the project was ready.

To see if it working I tried run your sample:
```

import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {ExchangeService, Folder, Item, ExchangeVersion, Uri, AttendeeInfo, TimeWindow, DateTime, AvailabilityData, ExchangeCredentials} from 'ews-js-api-browser';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {
    var exch = new ExchangeService(ExchangeVersion.Exchange2013_SP1);
    exch.Credentials = new ExchangeCredentials("username", "pass")
    exch.Url = new Uri("https://MyExchangeUrl/EWS/Exchange.asmx");

    var attendee = [new AttendeeInfo("attendee@myexchange.com")];
    var timeWindow = new TimeWindow(DateTime.Now, DateTime.Now.AddDays(2));

    exch.GetUserAvailability(attendee, timeWindow, AvailabilityData.FreeBusyAndSuggestions)
    .then(
      function (availResponse){}, 
      function(errors){}
    );
    

    console.log("Test");
  }

}
````

But if I try to build the project now I get the following error:

```
Cannot create an instance of the abstract class 'ExchangeCredentials'.

      L12:  var exch = new ExchangeService(ExchangeVersion.Exchange2013_SP1);
      L13:  exch.Credentials = new ExchangeCredentials("username", "pass")
      L14:  exch.Url = new Uri("https://MyExchangeUrl/EWS/Exchange.asmx");

Error: Failed to transpile program
    at new BuildError (...\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at ...\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (...\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (...\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at ...\node_modules\@ionic\app-scripts\dist\build.js:109:82
    at <anonymous>
````

**Comment by gautamsi** [comment]
use `WebCredentials` class rather than `ExchangeCredentials` this is now correctly listed as abstract class and typescript is not happy about it.
