### ISSUE TITLE
ConversationIndex Inaccessible in 2007

### ISSUE THREAD

**Issue by demarius** [gautamsi/ews-javascript-api#27]
See these two stackoverflow posts:
http://stackoverflow.com/questions/24490464/conversationid-property-vs-conversationindex-property-in-exchange-web-services-m
http://stackoverflow.com/questions/7487570/implementing-outlook-2010s-group-by-conversation-using-ews-and-exchange-2007

Try this in the console:
```
> new ews.ExtendedPropertyDefinition(ews.EmailMessageSchema.ConversationIndex, ews.MapiPropertyType.Binary)
[ByteArrayPropertyDefinition.Parse] ByteArrayPropertyDefinition needs to be improved
Error: ByteArrayPropertyDefinition: incorrect call of ToString(value): value is undefined
    at ByteArrayPropertyDefinition.ToString (/Users/demi/git/ecma/switchedon/sync/node_modules/ews-javascript-api/js/PropertyDefinitions/ByteArrayPropertyDefinition.js:64:15)
    at ByteArrayPropertyDefinition.TypedPropertyDefinition.toString (/Users/demi/git/ecma/switchedon/sync/node_modules/ews-javascript-api/js/PropertyDefinitions/TypedPropertyDefinition.js:68:21)
    at new ExtendedPropertyDefinition (/Users/demi/git/ecma/switchedon/sync/node_modules/ews-javascript-api/js/PropertyDefinitions/ExtendedPropertyDefinition.js:32:21)
```

**Comment by gautamsi** [comment]
Will lokk into this over weekend

**Comment by gautamsi** [comment]
ExtendedPropertyDefinition does not accept a property definition as argument. See what is accepts. 
```
   constructor();
    constructor(mapiType: MapiPropertyType);
    constructor(tag: number, mapiType: MapiPropertyType);
    constructor(propertySet: DefaultExtendedPropertySet, name: string, mapiType: MapiPropertyType);
    constructor(propertySet: DefaultExtendedPropertySet, id: number, mapiType: MapiPropertyType);
    constructor(propertySetId: Guid, name: string, mapiType: MapiPropertyType);
    constructor(propertySetId: Guid, id: number, mapiType: MapiPropertyType);
```

**Comment by gautamsi** [comment]
furthermore, you may not use following two constructor as they are marked internal. not exposed outside of library.  c# counterpart https://msdn.microsoft.com/en-us/library/office/microsoft.exchange.webservices.data.extendedpropertydefinition.extendedpropertydefinition(v=exchg.80).aspx
```
constructor();
constructor(mapiType: MapiPropertyType);
```

**Comment by gautamsi** [comment]
no activity, closing. please reopen if facing same problem.
