### ISSUE TITLE
EWS StreamSubscription hangs when network gets up from the crash

### ISSUE THREAD

**Issue by brt-chetan-mk** [gautamsi/ews-javascript-api#271]
Environment: Exchange 2010
Node 8.9.4
Platform:Linux 4.4.0-47-generic #68-Ubuntu SMP x86_64 GNU/Linux

The following typescript fails to re-connect EWS:
// Code //
const folderId: FolderId[] = [new FolderId(
      WellKnownFolderName.Calendar, new Mailbox(mailbox))];
const stream = await service.SubscribeToStreamingNotifications(
      folderId, EventType.Created, EventType.Modified, EventType.Moved);
    // Timeout is set at 30 minutes 
    const conn = new StreamingSubscriptionConnection(service, [stream], 30);
    const startStrmNotification =
      async (sender: StreamingSubscriptionConnection) => {
      while (!this.stopping) {
        try {
          log.verbose("EWS StreamSubscription open:", room);
          await sender.Open();
          break;
        } catch (err) {
          log.info("Failed to open stream notification for room",
                   room, err, err.stack);
          sender.AddSubscription(stream);
          await new Promise((resolve) => setTimeout(resolve, 1000));
        }
      }
    };
    const eventCb = async (sender: any, args: NotificationEventArgs) => {
      roomBlocker.lock(room);
      for (const notification of args.Events) {
        if (notification instanceof ItemEvent) {
          if (this.stopping) {
            break;
          }
          try {
            await this.handleNotification(service, room,
              notification.ItemId.UniqueId,
              notification.EventType);
          } catch (error) {
            log.silly("Stream notification error:", error);
            continue;
          }
        }
      }
      roomBlocker.unlock(room);
    };
    const disconnCb = async (sender: StreamingSubscriptionConnection) => {
      if (this.rooms.has(room)) {
        startStrmNotification(sender);
      } else {
        log.verbose("EWS StreamSubscription close:", room);
        try {
          await this.removeRoom(room);
        } catch (err) {
          return;
        }
      }
    };
    const errCb = async (sender: any, args: SubscriptionErrorEventArgs) => {
      log.info(`EWS stream notification for room ${room} error:`,
        args.Exception.Message);
      try {
        await sender.Close();
      } catch (err) {
        log.silly("Failed to close stream notification for", room);
      }
      await disconnCb(sender);
    };
    conn.OnNotificationEvent.push(eventCb);
    conn.OnSubscriptionError.push(errCb);
    conn.OnDisconnect.push(disconnCb);
    // Open connected
    startStrmNotification(conn);

Below is the error message I receive when it is trying to connect to EWS:
// Error //
  
13:48:31 - info: EWS stream notification for room testroom1@mrbstest.com error: The specified subscription was not found.
13:48:31 - silly: Failed to close stream notification for xxxx@yyyy.com
13:48:31 - verbose: EWS StreamSubscription open: xxxx@yyyy.com
13:48:31 - verbose: EWS StreamSubscription open: xxxx@yyyy.com
13:48:31 - info: Failed to open stream notification for room xxxx@yyyy.com ServiceLocalException {
  message: 'You must add at least one subscription to this connection before it can be opened.',
  InnerException: null } Exception: You must add at least one subscription to this connection before it can be opened.
    at StreamingSubscriptionConnection.Open (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:316:19)
    at startStrmNotification (/home/pi/Pre_Alpha/hub/src/ews.ts:359:34)
    at disconnCb (/home/pi/Pre_Alpha/hub/src/ews.ts:389:17)
    at InternalOnDisconnect.OnDisconnect.forEach (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:200:63)
    at Array.forEach (<anonymous>)
    at StreamingSubscriptionConnection.InternalOnDisconnect (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:200:35)
    at StreamingSubscriptionConnection.OnRequestDisconnect (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:302:14)
    at InternalOnDisconnect.OnDisconnect.forEach (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:162:25)
    at Array.forEach (<anonymous>)
    at GetStreamingEventsRequest.InternalOnDisconnect (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:161:39)
    at GetStreamingEventsRequest.Disconnect (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:46:18)
    at GetStreamingEventsResponse.ReadElementsFromXmlJsObject (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Responses/GetStreamingEventsResponse.js:78:30)
    at GetStreamingEventsResponse.LoadFromXmlJsObject (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Responses/ServiceResponse.js:121:22)
    at GetStreamingEventsRequest.ParseResponse (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Requests/GetStreamingEventsRequest.js:59:18)
    at GetStreamingEventsRequest.ReadResponseXmlJsObject (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:315:32)
    at GetStreamingEventsRequest.ParseResponses (/home/pi/Pre_Alpha/hub/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:177:39)

Any help would be appreciated.

**Comment by gautamsi** [comment]
turn on debug log and look for soap request, is it sending correct subscription id after failure?

**Comment by brt-chetan-mk** [comment]
Hi Gautam,

Thnks for ur reply.

I do not get the soap request as I'm dealing the connection through Node Js API service. I debug the code found the same subscription id while connection is being established and after network failure also.

Below is the debug log copied as is: It's the same before and after network failure.

/usr/local/bin/npm run serve 
Debugger listening on ws://127.0.0.1:9229/df6d22d1-2d64-48f1-b8ab-2c71ed88ce04
Debugger attached.

conn
StreamingSubscriptionConnection {subscriptions: DictionaryWithStringKey, connectionTimeout: 30, session: ExchangeService, isDisposed: false, currentHangingRequest: null, …}
connectionTimeout: 30
currentHangingRequest: null
CurrentSubscriptions: Array(1)
length: 1
__proto__: Array(0) [, …]
0: StreamingSubscription {service: ExchangeService, id: "HwBtcmJzZnR0ZXN0ZXhjaC5tcmJzZnR0ZXN0LmxvY2FsEAAAAE…", watermark: null}
**id: "HwBtcmJzZnR0ZXN0ZXhjaC5tcmJzZnR0ZXN0LmxvY2FsEAAAAE2EbRrMwm9Jusm4IAATPh+jRgBG9fjVCA=="
Id: "HwBtcmJzZnR0ZXN0ZXhjaC5tcmJzZnR0ZXN0LmxvY2FsEAAAAE2EbRrMwm9Jusm4IAATPh+jRgBG9fjVCA=="**
service: ExchangeService {requestedServerVersion: 3, timeZone: TimeZoneInfo, xhrApi: ntlmAuthXhrApi, …}
Service: ExchangeService
UsesWatermark: false
watermark: null
Watermark: null
__proto__: SubscriptionBase {constructor: , Service: <accessor>, UsesWatermark: <accessor>, …}
isDisposed: false
IsOpen: false
lockObject: Object {isLocked: false}
OnDisconnect: Array(0) []
OnNotificationEvent: Array(0) []
OnResponseHeader: Array(0) []
OnSubscriptionError: Array(0) []
session: ExchangeService {requestedServerVersion: 3, timeZone: TimeZoneInfo, xhrApi: ntlmAuthXhrApi, …}
subscriptions: DictionaryWithStringKey {keys: Array(1), keysToObjs: Object, objects: Object, …}
__proto__: Object {constructor: , CurrentSubscriptions: <accessor>, IsOpen: <accessor>, …}
10:59:45 - debug: Request PanL3-12 set room name to xxxx
10:59:45 - debug: GetTimeline: PanL3-12 255 slots from Yesterday at 12:00 AM
10:59:45 - debug: GetTimeline: PanL3-12 255 slots from Today at 12:00 AM
11:02:45 - debug: expired: xxxx@yyyy.com:20180802

**Comment by brt-chetan-mk** [comment]
Even, the exchange service is holding same piece of data during connection was established.

**Comment by gautamsi** [comment]
set `EwsLogging.DebugLogEnabled = true` right after you import lib first time. this way you will see all the ews soap logs. check if the subsequent request is sending correct subscription id

**Comment by brt-chetan-mk** [comment]
@gautamsi 

Thank you for your time.
The issue is resolved after adding ciphers: 'DES-CBC3-SHA' to request options.
