### ISSUE TITLE
Not able to send reply to an EmailMessage

### ISSUE THREAD

**Issue by rousselle** [gautamsi/ews-javascript-api#284]
I am trying to send a reply to an EmailMessage. Please let me know if I'm doing something wrong (I'm pretty sure I am not, I checked the case on everything) or if there is a work around. The session below shows the error. Email addresses and passwords are redacted. Thank You
```
> var exch = new ews.ExchangeService(4);
undefined
> exch.Url = new ews.Uri("https://" + 'us.exg7.exghost.com' + "/Ews/Exchange.asmx");
Uri {
  m_scheme: 'https',
  url: 'https://us.exg7.exghost.com/Ews/Exchange.asmx' }
> exch.Credentials = new ews.ExchangeCredentials(<redacted>, <redacted>);
ExchangeCredentials {
  UserName: <redacted>,
  setPassword: [Function],
  getPassword: [Function] }
> uid = "AAMkADljNGUzMTIzLTJkYTMtNDVkNS05YjBhLWUzODhiYWExYmJkMQBGAAAAAAAB2AKipAzITJD/sJi+/PizBwAQfNcAdywBRJBBywz/0Cz4AAAAAAEMAAAQfNcAdywBRJBBywz/0Cz4AAHHzRHpAAA=";
'AAMkADljNGUzMTIzLTJkYTMtNDVkNS05YjBhLWUzODhiYWExYmJkMQBGAAAAAAAB2AKipAzITJD/sJi+/PizBwAQfNcAdywBRJBBywz/0Cz4AAAAAAEMAAAQfNcAdywBRJBBywz/0Cz4AAHHzRHpAAA='
> iid = new ews.ItemId(uid);
ItemId {
  Namespace: 2,
  OnChange: [],
  UniqueId: 'AAMkADljNGUzMTIzLTJkYTMtNDVkNS05YjBhLWUzODhiYWExYmJkMQBGAAAAAAAB2AKipAzITJD/sJi+/PizBwAQfNcAdywBRJBBywz/0Cz4AAAAAAEMAAAQfNcAdywBRJBBywz/0Cz4AAHHzRHpAAA=' }
> var result;
undefined
> var error;
undefined
> ews.EmailMessage.Bind(exch, iid).then(response => result = response).catch(rejection => error = rejection);
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> result;
EmailMessage {
  lockObject: {},
  OnChange: [],
  setService: [Function],
  getService: [Function],
  propertyBag: 
   PropertyBag {
     owner: [Circular],
     isDirty: false,
     loading: false,
     onlySummaryPropertiesRequested: false,
     loadedProperties: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     properties: 
      DictionaryWithPropertyDefitionKey {
        keys: [Array],
        keysToObjs: [Object],
        objects: [Object],
        keyPicker: [Function] },
     deletedProperties: DictionaryWithPropertyDefitionKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
     modifiedProperties: [],
     addedProperties: [],
     requestedPropertySet: 
      PropertySet {
        basePropertySet: 1,
        additionalProperties: [],
        requestedBodyType: null,
        requestedUniqueBodyType: null,
        requestedNormalizedBodyType: null,
        filterHtml: null,
        convertHtmlCodePageToUTF8: null,
        inlineImageUrlTemplate: null,
        blockExternalImages: null,
        addTargetToLinks: null,
        isReadOnly: true,
        maximumBodySize: null } },
  parentAttachment: null }
> var reply = result.CreateReply(false);
undefined
> reply.BodyPrefix = "This is a reply sent from the EWS API package";
'This is a reply sent from the EWS API package'
> var sendResult;
undefined
> var sendError;
undefined
> reply.SendAndSaveCopy().then(response => sendResult = response).catch(error => sendError = error);
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> sendError;
TypeError: complexProperty.WriteToXml is not a function
    at ComplexPropertyDefinitionBase.WritePropertyValueToXml (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/PropertyDefinitions/ComplexPropertyDefinitionBase.js:101:29)
    at PropertyBag.WriteToXml (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/PropertyBag.js:577:40)
    at ResponseMessage.ServiceObject.WriteToXml (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/ServiceObjects/ServiceObject.js:317:79)
    at CreateResponseObjectRequest.CreateRequest.WriteElementsToXml (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/CreateRequest.js:64:17)
    at CreateResponseObjectRequest.ServiceRequestBase.WriteBodyToXml (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:460:14)
    at CreateResponseObjectRequest.ServiceRequestBase.WriteToXml (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:529:14)
    at CreateResponseObjectRequest.ServiceRequestBase.EmitRequest (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:165:18)
    at CreateResponseObjectRequest.ServiceRequestBase.BuildXHR (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:131:14)
    at /Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:50:33
    at Promise._execute (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/bluebird/js/release/promise.js:79:10)
    at CreateResponseObjectRequest.SimpleServiceRequestBase.InternalExecute (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:49:16)
    at /Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:45:19
    at Promise._execute (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/philiprousselle/Projects/nexd/modules/integration-mail/node_modules/bluebird/js/release/promise.js:483:18)
> reply;
ResponseMessage {
  lockObject: {},
  OnChange: [],
  setService: [Function],
  getService: [Function],
  propertyBag: 
   PropertyBag {
     owner: [Circular],
     isDirty: true,
     loading: false,
     onlySummaryPropertiesRequested: false,
     loadedProperties: [],
     properties: 
      DictionaryWithPropertyDefitionKey {
        keys: [Array],
        keysToObjs: [Object],
        objects: [Object],
        keyPicker: [Function] },
     deletedProperties: DictionaryWithPropertyDefitionKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
     modifiedProperties: [],
     addedProperties: [ [Object] ],
     requestedPropertySet: null },
  referenceItem: 
   EmailMessage {
     lockObject: {},
     OnChange: [],
     setService: [Function],
     getService: [Function],
     propertyBag: 
      PropertyBag {
        owner: [Circular],
        isDirty: false,
        loading: false,
        onlySummaryPropertiesRequested: false,
        loadedProperties: [Array],
        properties: [Object],
        deletedProperties: [Object],
        modifiedProperties: [],
        addedProperties: [],
        requestedPropertySet: [Object] },
     parentAttachment: null },
  responseType: 0 }
```

**Comment by gautamsi** [comment]
there is no operator overloading in JS, use constructor for [MessageBody](https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.messagebody_members(v=exchg.80).aspx#Anchor_0)

```js
reply.BodyPrefix = new ews.MessageBody("This is a reply sent from the EWS API package");
```

**Comment by rousselle** [comment]
Thanks
