### ISSUE TITLE
<service>.FindAppointments failing inside promise.

### ISSUE THREAD

**Issue by roeintense** [gautamsi/ews-javascript-api#285]
Gautamsi,

Thanks for all you do. 

I have a call I'm making to <service>.FindAppointments. I use the exact code, with the exception of the variables I need for my environment, as the code you have [here](https://gist.github.com/gautamsi/ba0561da1b4a2b29478943ba5f002328). This is what keeps happening to me. The promise is erroring and I have no idea why. Please advise.

```
"Error
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/gar573/repo/upe/node_modules/bluebird/js/release/debuggability.js:411:19)
    at Promise._then (/home/gar573/repo/upe/node_modules/bluebird/js/release/promise.js:232:17)
    at Promise.then (/home/gar573/repo/upe/node_modules/bluebird/js/release/promise.js:125:17)
    at Promise.caught.Promise.catch (/home/gar573/repo/upe/node_modules/bluebird/js/release/promise.js:106:17)
    at eval (eval at connection.OnNotificationEvent.push (/home/gar573/repo/upe/listener.js:58:11), <anonymous>:1:113)
    at connection.OnNotificationEvent.push (/home/gar573/repo/upe/listener.js:58:11)
    at /home/gar573/repo/upe/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:264:93
    at Array.forEach (<anonymous>)
    at _loop_1 (/home/gar573/repo/upe/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:264:52)
    at StreamingSubscriptionConnection.IssueNotificationEvents (/home/gar573/repo/upe/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:273:13)
    at StreamingSubscriptionConnection.HandleServiceResponseObject (/home/gar573/repo/upe/node_modules/ews-javascript-api/js/Notifications/StreamingSubscriptionConnection.js:182:26)
    at GetStreamingEventsRequest.HangingServiceRequestBase.ParseResponses (/home/gar573/repo/upe/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:194:18)
    at /home/gar573/repo/upe/node_modules/ews-javascript-api/js/Core/Requests/HangingServiceRequestBase.js:102:39
    at FetchStream.<anonymous> (/home/gar573/repo/upe/node_modules/ews-javascript-api-auth/src/ntlmAuthXhrApi.js:89:21)
    at emitOne (events.js:115:13)
    at FetchStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at FetchStream.Readable.push (_stream_readable.js:209:10)
    at FetchStream.drainBuffer (/home/gar573/repo/upe/node_modules/fetch/lib/fetch.js:84:14)
    at FetchStream.<anonymous> (/home/gar573/repo/upe/node_modules/fetch/lib/fetch.js:326:22)
    at emitOne (events.js:115:13)"
```

**Comment by gautamsi** [comment]
I would say it is unrelated to FindAppointments, I see that you are using `StreamingSubscriptionConnection` or related code for streaming events. can you share your code block in gitter 1:1

**Comment by roeintense** [comment]
Unfortunately no, but I'll redact some things here. Does this help?

```
exch.ImpersonatedUserId = new ews.ImpersonatedUserId(ews.ConnectingIdType.SmtpAddress, 
exch
  .SubscribeToStreamingNotifications(
    [new ews.FolderId(ews.WellKnownFolderName.Calendar)],
    ews.EventType.Deleted,
    ews.EventType.Created,
    ews.EventType.Deleted,
    ews.EventType.Modified,
    ews.EventType.Moved,
    ews.EventType.Copied
  )
  .then(
    streamingSubscription => {
      // Create a streaming connection to the service object, over which events are ret
      // Keep the streaming connection open for 30 minutes.
      let connection = new ews.StreamingSubscriptionConnection(exch, 30);
      //logger.log('Connection: \n' + connection);
      connection.AddSubscription(streamingSubscription);
      connection.OnNotificationEvent.push((o, a) => {
        logger.log('info', 'notification received for ' + user); //this gives you each 
        //ews.EwsLogging.Log(a, true, true);
        // logger.log('info', a);
        let itemId = a.Events[1].ItemId;

        var attendee = [new ews.AttendeeInfo(user)];
        //create timewindow object o request avaiability suggestions for next 48 hours,
n object using momentjs
        var view = new ews.CalendarView(ews.DateTime.Now, ews.DateTime.Now.AddDays(1));
        debugger;
        exch
          .FindAppointments(ews.WellKnownFolderName.Calendar, view)
          .then(response => {
    let appointments = response.Items;
    let appointment = appointments[0];
    debugger;
    console.log('Subject: ' + appointment.Subject);
    console.log('Start Time: ' + appointment.Start);
    console.log('End Time: ' + appointment.End);
    console.log('Recipients: ');
    appointment.RequiredAttendees.Items.forEach(a => {
      console.log(a.Address);
    });
    console.log('unique id: ' + appointment.Id.UniqueId, true, true);
  })
  .catch(error => {
    console.log(error);
  });
debugger;
```

**Comment by gautamsi** [comment]
this line:
```
let itemId = a.Events[1].ItemId;
```

if there is only one event, it will error out and break the promise.

**Comment by roeintense** [comment]
That previous comment was a good catch, but it was not what was causing the problem. Although I have still not isolated what my problem was, I implemented the following to a successful resolution:

```
let f = new ews.FolderId(ews.WellKnownFolderName.Calendar, new ews.Mailbox(user));
let view = new ews.CalendarView(ews.DateTime.Now, ews.DateTime.Now.AddDays(1));

exch.FindAppointments(f, view).then( events => {
    console.log(events)
}
```
