### ISSUE TITLE
Cannot read property 'documentElement' of undefined

### ISSUE THREAD

**Issue by PhilHannent** [gautamsi/ews-javascript-api#330]
We have a service which relies on this library, early this morning we got a bunch of errors which read:

`Cannot read property 'documentElement' of undefined
    at EwsServiceXmlReader.EwsXmlReader (C:\Elmstone\Websites\room-booking-api-prod\node_modules\ews-javascript-api\src\js\Core\EwsXmlReader.js:18:57)
    at new EwsServiceXmlReader (C:\Elmstone\Websites\room-booking-api-prod\node_modules\ews-javascript-api\src\js\Core\EwsServiceXmlReader.js:22:28)
    at FindItemRequest.ServiceRequestBase.ProcessWebException (C:\Elmstone\Websites\room-booking-api-prod\node_modules\ews-javascript-api\src\js\Core\Requests\ServiceRequestBase.js:262:30)
    at C:\Elmstone\Websites\room-booking-api-prod\node_modules\ews-javascript-api\src\js\Core\Requests\SimpleServiceRequestBase.js:83:41
    at tryCatcher (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Elmstone\Websites\room-booking-api-prod\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

The error was transient and only lasted a minute. Prior to it there was a soap fault:

`SoapFaultDetails {
  message: 'connect ECONNREFUSED 217.13.158.190:443',
  InnerException: null,
  faultCode: null,
  faultString: null,
  faultActor: null,
  responseCode: 127,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails:
   DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: undefined }`

So it looks like the remote service was restarting and the EWS library got some unexpected data.

I don't have any other details at this time, but this caused the app to restart.

**Comment by gautamsi** [comment]
looks like there were connection issue, are you able to run this again?

**Comment by PhilHannent** [comment]
The problem was resolved by the service restarting itself. Me raising this ticket is because the error propagated to `process.on('unhandledRejection')` which would have restarted the node process (not ideal).

We currently using this branch and this is the location of the crash:
https://github.com/dnaustin/ews-javascript-api/blob/master/src/js/Core/EwsXmlReader.js#L18

(We're using this fork whilst we wait for your 0.10 with the new HttpResponseHeaders which you did in response to: https://github.com/gautamsi/ews-javascript-api/pull/320 )

95% of our problems are with Office 365 EWS giving back unexpected values which this library isn't trapping or the connection is rejected/closed randomly (probably because of it being a 24/7 system and Azure move things around internally).

It would be great if this (https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/EwsXmlReader.ts#L43) knew it didn't get back the expected XML and was able to know it got back something other than XML.

At this point I'm imagining the response back is from the Microsoft Load Balancer sending some diagnostic/error HTML message. But it's a random occurrence to not something we can reproduce.

**Comment by gautamsi** [comment]
`0.10` is released, please close this issue if it is not an issue anymore.

**Comment by PhilHannent** [comment]
I'm closing this issue as it's intermittent and not something I can trigger on demand. I've updated to 0.10 and will run tests this week.

Thanks a lot for releasing 0.10
