### ISSUE TITLE
Setting of custom headers not working in v0.10.0

### ISSUE THREAD

**Issue by KaskMartin** [gautamsi/ews-javascript-api#337]
Setting custom headers that used to work in v0.9.6 is not working after upgrading the library.

Example code used:
```javascript
const ews = require('ews-javascript-api');
const { escape } = require('lodash');
const outlookService = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);

outlookService.Url = new ews.Uri('https://outlook.office365.com/EWS/Exchange.asmx');
outlookService.Credentials = new ews.WebCredentials("your_office365_username", "your_office365_password");

const outlookMessage = new ews.EmailMessage(outlookService);

outlookMessage.Body = new ews.MessageBody(
    ews.BodyType.HTML,
    escape(`<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></head><body>testing1234</body></html>`)
);
outlookMessage.ToRecipients.Add(
    new ews.EmailAddress("","test_email@address.com")
);

const customHeaderProperty = new ews.ExtendedPropertyDefinition(
    ews.DefaultExtendedPropertySet.InternetHeaders,
    "customheadername",
    ews.MapiPropertyType.String
);

try {
    outlookMessage.SetExtendedProperty(customHeaderProperty, "customheadervalue");
} catch (err) {
    console.log(err);
// err.message = "Cannot read property 'RequestedServerVersion' of null"
// err.stack = "TypeError: Cannot read property 'RequestedServerVersion' of null
// at PropertyBag.GetPropertyValueOrException (/app/node_modules/ews-javascript-api/js/Core/PropertyBag.js:269:61)
// at PropertyBag._getItem (/app/node_modules/ews-javascript-api/js/Core/PropertyBag.js:81:34)
// at EmailMessage.get [as ExtendedProperties] (/app/node_modules/ews-javascript-api/js/Core/ServiceObjects/Items/Item.js:499:37)
// at EmailMessage.Item.SetExtendedProperty (/app/node_modules/ews-javascript-api/js/Core/ServiceObjects/Items/Item.js:923:94)
// ..."
}
await outlookMessage.SendAndSaveCopy(ews.WellKnownFolderName.SentItems)
```

**Comment by gautamsi** [comment]
I am having no issues in working with this code. which version you used?

**Comment by gautamsi** [comment]
reopen if you still have thi issue
