### ISSUE TITLE
Getting 401 Unauthorized access

### ISSUE THREAD

**Issue by ali-bugdayci** [gautamsi/ews-javascript-api#338]
Hi,

First of all I would like to thank you for such a great project since I can use my own environment for connecting to Exchange server.

I am using the trial Contoso Exchange Server 2010 (version 14.1.218.0) that Microsoft provides. I am getting 401 Unauthorized access:

```
sending ews request
{ url: 'https://exchange.myServer.com/Ews/Exchange.asmx',
  headers: 
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     'Accept-Encoding': 'gzip,deflate',
     Authorization: 'REDACTED' },
  type: 'POST',
  data: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2010_SP1"></t:RequestServerVersion></soap:Header><soap:Body><m:CreateItem MessageDisposition="SendOnly"><m:Items><t:Message><t:Subject>Dentist Appointment</t:Subject><t:Body BodyType="HTML">The appointment is with Dr. Smith.</t:Body><t:ToRecipients><t:Mailbox><t:EmailAddress>BenM@contoso.com</t:EmailAddress></t:Mailbox></t:ToRecipients></t:Message></m:Items></m:CreateItem></soap:Body></soap:Envelope>' }
Error in calling service, error code:401
server : Microsoft-IIS/7.5
set-cookie : exchangecookie=2059bacce69f4592986248d2597a9c03; expires=Thu, 28-Jan-2021 17:59:37 GMT; path=/; HttpOnly
www-authenticate : Negotiate, NTLM
x-powered-by : ASP.NET
date : Tue, 28 Jan 2020 17:59:37 GMT
connection : close
content-length : 0

SoapFaultDetails {
  message: '401 Unauthorized',
  stack: [Getter/Setter],
  InnerException: null,
  faultCode: null,
  faultString: null,
  faultActor: null,
  responseCode: 127,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: 401,
  Exception: 
   ServiceRequestUnauthorizedException {
     message: '401 Unauthorized',
     stack: [Getter/Setter],
     InnerException: null } }
```

I gave the EWS access to both user and organization:

https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-control-access-to-ews-in-exchange

I returned back to writing a basic mail, since I am also getting it via Subscription. But it still gives me 401.

Here is my code:

```
"use strict";

var ews = require('ews-javascript-api');
var service = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP1);
var credentials = require("./credentials.json");

ews.EwsLogging.DebugLogEnabled = true;

ews.ConfigurationApi.SetXHROptions({rejectUnauthorized : false});

service.Credentials = new ews.ExchangeCredentials(credentials.userName, credentials.password);
service.Url = new ews.Uri("https://exchange.myServer.com/Ews/Exchange.asmx");
//service.Url = new ews.Uri("http://SLC-DC01.contoso.com/Ews/Exchange.asmx");


var msgattach = new ews.EmailMessage(service);
msgattach.Subject = "Dentist Appointment";
msgattach.Body = new ews.MessageBody("The appointment is with Dr. Smith.");
msgattach.ToRecipients.Add("BenM@contoso.com");

msgattach.Send().then(function() {
	console.log("Send");
}, function(ei){
	ews.EwsLogging.Log(ei, true, true);
	console.log(ei.stack, ei.stack.split("\n"));
	console.log("------------");
});
```

And here are the credentials.json
```
{
"userName": "AaronC@contoso.com",
"password": "pass@word1"
}
```

Both URL's are not working (including SLC-DC01.contoso.com).

By the way, I configured the domain name URL to an in LAN machine which is the exchange server installed via hosts file:

```
ping SLC-DC01.contoso.com 
PING exchange.myServer.com (192.168.1.36) 56(84) bytes of data.
```

I can go and log in to the OWA page without any problem.

.Am I missing something? 

Thanks in advance.

**Comment by ali-bugdayci** [comment]
Hi,

I tried switching to ntlm API by adding:

```
var ewsAuth = require("ews-javascript-api-auth");
ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi(credentials.userName, credentials.password));
ews.ConfigurationApi.SetXHROptions({rejectUnauthorized : false});
```

1. Although I set reject unauthorized it is not connecting to http. Should I somehow set it over ewsAuth?

2. I used the https domain and getting now 500. Seems that I am still missing something.


```
sending ews request
{ url: 'https://exchange.myServer.com/Ews/Exchange.asmx',
  headers: 
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     'Accept-Encoding': 'gzip,deflate',
     Authorization: 'REDACTED' },
  type: 'POST',
  data: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2010_SP1"></t:RequestServerVersion></soap:Header><soap:Body><m:CreateItem MessageDisposition="SendOnly"><m:Items><t:Message><t:Subject>Dentist Appointment</t:Subject><t:Body BodyType="HTML">The appointment is with Dr. Smith.</t:Body><t:ToRecipients><t:Mailbox><t:EmailAddress>BenM@contoso.com</t:EmailAddress></t:Mailbox></t:ToRecipients></t:Message></m:Items></m:CreateItem></soap:Body></soap:Envelope>' }
Error in calling service, error code:500
cache-control : private
server : Microsoft-IIS/7.5
set-cookie : exchangecookie=cff18f69ed2c43139297e361f4e7449b; expires=Thu, 28-Jan-2021 18:39:49 GMT; path=/; HttpOnly
x-aspnet-version : 2.0.50727
persistent-auth : true
x-powered-by : ASP.NET
date : Tue, 28 Jan 2020 18:39:49 GMT
connection : close
content-length : 0

[xmldom error]  invalid doc source 
@#[line:0,col:undefined]
Unhandled rejection TypeError: Cannot read property 'documentElement' of undefined
    at EwsServiceXmlReader.EwsXmlReader (/server/node_modules/ews-javascript-api/js/Core/EwsXmlReader.js:18:56)
    at new EwsServiceXmlReader (/server/node_modules/ews-javascript-api/js/Core/EwsServiceXmlReader.js:22:28)
    at CreateItemRequest.ServiceRequestBase.ProcessWebException (/server/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:273:30)
    at /server/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:83:41
    at tryCatcher (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/server/node_modules/ews-javascript-api-auth/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```


3. Can I use ews-javascript-api for maintaining affinity over multiple user requests

https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-maintain-affinity-between-group-of-subscriptions-and-mailbox-server


Thanks

**Comment by gautamsi** [comment]
NTLM with gzip does not seems to work properly in your case, 

see this - https://github.com/gautamsi/ews-javascript-api/issues/334

**Comment by ali-bugdayci** [comment]
Hi,

Thank you for your response sir. 

I tried adding gzip:true but did not work.

I believe that the problem is not about gzip. Xml Dom Error is given because the response is empty meaning undefined:

```
[xmldom error]  invalid doc source 
@#[line:0,col:undefined]
Unhandled rejection TypeError: Cannot read property 'documentElement' of undefined
```

The content-length given below is also 0, so an empty response. The server side is giving me 500 error, which I think because of a misconfiguration on Exchange side:

```
Error in calling service, error code:500
cache-control : private
server : Microsoft-IIS/7.5
x-aspnet-version : 2.0.50727
persistent-auth : true
x-powered-by : ASP.NET
date : Wed, 29 Jan 2020 08:11:37 GMT
connection : close
content-length : 0
```

I am not sure but, I suppose since I am using Exchange Trial 2010 SP1 version (  https://www.microsoft.com/en-us/download/details.aspx?id=5002 ) the domain name is configured as 'SLC-DC01.contoso.com'.

Could it be because I am accessing it via adding my own domain to IIS (Sice I do not have ssl certs for contoso.com) e.g. 'exchange.myServer.com' and exchange EWS is not configured to accept requests from this domain ? Although OWA is working EWS might have a different configuration.

**Comment by gautamsi** [comment]
if you are using host headers in IIS then you have to use the correct url for calling this service.

**Comment by ali-bugdayci** [comment]
I am not sure what you mean by that.

When I go to 'https://exchange.myServer.com/Ews/Exchange.asmx' I can already see the xmlsoap schema definition without any problem. It is SSL secured and it can show me without any problem.

But this is possbily using IIS to respond. Should I also configure Exchange server?

Like in the exchange management shell, the following command gives me:

```
Get-WebServicesVirtualDirectory

InternalUrl                     : https://slc-dc01.contoso.com/EWS/Exchange.asmx
ExternalUrl                     : https://mail.contoso.com/ews/exchange.asmx
```

So if you have expertise on exchange server configuration, can you share me what I need to chage in order to make another external domain to work with EWS.

Thanks in advance

**Comment by gautamsi** [comment]
have you tried the code snippet of c# version? if that works this will work too.

internal and external both url should work depends upon where are you calling.

**Comment by ali-bugdayci** [comment]
I believe it is related to the Exchange installation, I installed a fresh one and not getting the errors anymore.

Thanks
