### ISSUE TITLE
NTLM/ntlmXHR using impersonation

### ISSUE THREAD

**Issue by maccyber** [gautamsi/ews-javascript-api#34]
Hey, I'm trying to use impersonation to get users tasks in exchange.
Is it possible with this API?

This (https://gist.github.com/maccyber/a57e3b7f8ded3d72205c817cf4c5b377) code, gives: 
```
Error: Id property must be set before serialization
    at ImpersonatedUserId.WriteToXml (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Misc/ImpersonatedUserId.js:16:19)
    at FindItemRequest.ServiceRequestBase.WriteToXml (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:402:45)
    at FindItemRequest.ServiceRequestBase.EmitRequest (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:102:18)
    at FindItemRequest.ServiceRequestBase.BuildXHR (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:73:14)
    at /home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:41:33
    at new Promise (/home/jonas/projects/ews-tasks-exchange/node_modules/winjs-node/src/js/WinJS/Promise/_StateMachine.js:988:13)
    at WinJSPromiseApi.create (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Promise_WinJS.js:12:16)
    at Function.PromiseFactory.create (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/PromiseFactory.js:32:30)
    at FindItemRequest.SimpleServiceRequestBase.InternalExecute (/home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:40:48)
    at /home/jonas/projects/ews-tasks-exchange/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:36:19
```

**Comment by maccyber** [comment]
Gave you a PR to fix this.
Now it gives me:
```js
sending ews request
{ url: 'https://url.no/ews/Exchange.asmx',
  headers: 
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     Authorization: 'Basic blablaW5cZW5najpWVFlGM0tjYSFubw==' },
  type: 'POST',
  data: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion><t:ExchangeImpersonation><t:ConnectingSID><t:SmtpAddress>mail@mail.com</t:SmtpAddress></t:ConnectingSID></t:ExchangeImpersonation></soap:Header><soap:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>AllProperties</t:BaseShape></m:ItemShape><m:IndexedPageItemView MaxEntriesReturned="20" Offset="0" BasePoint="Beginning"></m:IndexedPageItemView><m:Restriction><t:IsNotEqualTo><t:FieldURI FieldURI="task:IsComplete"></t:FieldURI><t:FieldURIOrConstant><t:Constant Value="true"></t:Constant></t:FieldURIOrConstant></t:IsNotEqualTo></m:Restriction><m:ParentFolderIds><t:DistinguishedFolderId Id="tasks"></t:DistinguishedFolderId></m:ParentFolderIds></m:FindItem></soap:Body></soap:Envelope>' }
{ __prefix: 'soap',
  __xmlns: 
   { soap: 'http://schemas.xmlsoap.org/soap/envelope/',
     xsi: 'http://www.w3.org/2001/XMLSchema-instance',
     m: 'http://schemas.microsoft.com/exchange/services/2006/messages',
     t: 'http://schemas.microsoft.com/exchange/services/2006/types' },
  Header: 
   { __prefix: 'soap',
     RequestServerVersion: 
      { __prefix: 't',
        __type: 'RequestServerVersion',
        Version: 'Exchange2013' },
     ExchangeImpersonation: 
      { __prefix: 't',
        __type: 'ExchangeImpersonation',
        ConnectingSID: 
         { __prefix: 't',
           __type: 'ConnectingSID',
           SmtpAddress: 'mail@mail.com' } } },
  Body: 
   { __prefix: 'soap',
     FindItem: 
      { __prefix: 'm',
        Traversal: 'Shallow',
        ItemShape: { __prefix: 'm', BaseShape: 'AllProperties' },
        IndexedPageItemView: 
         { __prefix: 'm',
           MaxEntriesReturned: '20',
           Offset: '0',
           BasePoint: 'Beginning' },
        Restriction: 
         { __prefix: 'm',
           IsNotEqualTo: 
            { __prefix: 't',
              __type: 'IsNotEqualTo',
              FieldURI: 
               { __prefix: 't',
                 __type: 'FieldURI',
                 FieldURI: 'task:IsComplete' },
              FieldURIOrConstant: 
               { __prefix: 't',
                 __type: 'FieldURIOrConstant',
                 Constant: { __prefix: 't', __type: 'Constant', Value: 'true' } } } },
        ParentFolderIds: 
         { __prefix: 'm',
           DistinguishedFolderId: { __prefix: 't', __type: 'DistinguishedFolderId', Id: 'tasks' } } } } }
[MultiResponseServiceRequest.Execute] ServiceErrorHandling.ThrowOnError error handling is only valid for singleton request

```

**Comment by maccyber** [comment]
Gave you a PR #35  to fix this.

**Comment by gautamsi** [comment]
merged.
