### ISSUE TITLE
GetServerTimeZones crashes

### ISSUE THREAD

**Issue by perbergland** [gautamsi/ews-javascript-api#363]
I was just trying to get the timezones from the server but the call crashed with

TypeError: Cannot read property 'AddDays' of undefined
    at TimeZoneDefinition.ToTimeZoneInfo (node_modules/ews-javascript-api/js/ComplexProperties/TimeZones/TimeZoneDefinition.js:260:44)
    at GetServerTimeZonesResponse.ReadElementsFromXmlJsObject (node_modules/ews-javascript-api/js/Core/Responses/GetServerTimeZonesResponse.js:56:56)

Is this a known issue? Is there a workaround?

I'll dig a bit more to see if I can find the offending data entry.

**Comment by perbergland** [comment]
I found the static method TimeZoneInfo.Find... and it worked just fine without a server call so this is low priority to fix for me
