### ISSUE TITLE
Unhandled rejection Error: incorrect header check

### ISSUE THREAD

**Issue by fastsyrup** [gautamsi/ews-javascript-api#367]
Hi,

Developing a chrome extension which accesses Exchange Inbox from a background script (to avoid CORS issues).
Unfortunately I get a "Unhandled rejection Error: incorrect header error.

My code
` var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);`
`exch.Credentials = new ews.WebCredentials(username, password);`
`exch.Url = new ews.Uri("https://outlook.office365.com/Ews/Exchange.asmx");`
`var Inbox = ews.Folder.Bind(exch,ews.WellKnownFolderName.Inbox);`
`console.log(Inbox);`

The error in detail:

`background.js:formatted:4957 Unhandled rejection Error: incorrect header check    at Zlib._handle.onerror (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:25190:17)    at Zlib._error (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24709:8)    at Zlib._checkError (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24680:12)    at Zlib._after (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24688:13)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24552:10    at Item.run (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:3053:12)    at drainQueue (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:3017:34)From previous event:    at XHRDefault.xhr (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:28986:16)    at GetFolderRequest.ServiceRequestBase.ValidateAndEmitRequest (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:76982:36)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77186:19From previous event:    at GetFolderRequest.SimpleServiceRequestBase.InternalExecute (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77183:16)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77660:19From previous event:    at GetFolderRequest.MultiResponseServiceRequest.Execute (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77659:16)    at ExchangeService.BindToFolder (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:106772:24)    at Function.Folder.Bind (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:72167:28)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:117447:26    at Zlib._handle.onerror (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:25190:17)    at Zlib._error (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24709:8)    at Zlib._checkError (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24680:12)    at Zlib._after (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24688:13)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:24552:10    at Item.run (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:3053:12)    at drainQueue (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:3017:34)    at XHRDefault.xhr (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:28986:16)    at GetFolderRequest.ServiceRequestBase.ValidateAndEmitRequest (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:76982:36)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77186:19From previous event:    at GetFolderRequest.SimpleServiceRequestBase.InternalExecute (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77183:16)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77660:19From previous event:    at GetFolderRequest.MultiResponseServiceRequest.Execute (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:77659:16)    at ExchangeService.BindToFolder (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:106772:24)    at Function.Folder.Bind (chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:72167:28)    at chrome-extension://oopmdblhdbblcdhiiohdigppbbnakpjn/background.js:117447:26`

Could you please help me?

Thanks in advance!

**Comment by fastsyrup** [comment]
Sorry, tried ews-js-api-browser and it works...
