### ISSUE TITLE
Can't cancel meeting - TypeError

### ISSUE THREAD

**Issue by inkirby** [gautamsi/ews-javascript-api#99]
Hi again,

I've been trying to cancel a meeting with this approach:
- I bound an appointment with an unique id
- I called `CancelMeeting` on the appointment

But I got this error:
`TypeError: Cannot read property 'GetEnumerator' of undefined`

I've tried another approaches like: 
- `ExchangeService.DeleteItem`
- `Appointment.Delete`
- `Appointment.CreateCancelMeetingMessage.SendAndSaveCopy`

but EWS did just delete the meeting on "owner's" calendar and it did not send any update to the meeting attendees.

Do you have any suggestions?

Thanks in advance, once again.

The Code
---

ews.Appointment.Bind(exchangeService, new ews.ItemId(eventId)).done(function (rawAppointment) {

	rawAppointment.CancelMeeting("Meeting cancelled by service").done(function (result) {
		//Cancellation success
	}, function(err) {
		//Error on cancellation
	});

}, function(err) {
	//Error on binding
});

**Comment by gautamsi** [comment]
this is covered in #100, I still have to implement them.

**Comment by alitriki** [comment]
I'm having almost the same problem. when I execute this function :
````javascript
function deleteMeeting(id) {
    var meeting = new ews.Appointment(exch);
    ews.Appointment.Bind(exch, id).done(function (meeting) {

        meeting.CancelMeeting("Meeting cancelled by service").done(function (result) {
            //Cancellation success
            console.log("\n success");
        }, function (err) {
            //Error on cancellation
            console.log(err.stack);
        });

    }, (ei) => {
        console.log(ei.stack, ei.stack.split("\n"));
        console.log("------------");
    });

}
```` 
this is the result I'm getting : 
````
TypeError: Cannot read property 'GetEnumerator' of undefined                                                                                                                                         
    at PropertyBag.WriteToXml (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/PropertyBag.js:438:48)                                                                
    at CancelMeetingMessage.ServiceObject.WriteToXml (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/ServiceObjects/ServiceObject.js:316:79)                        
    at CreateResponseObjectRequest.CreateRequest.WriteElementsToXml (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/Requests/CreateRequest.js:56:17)                
    at CreateResponseObjectRequest.ServiceRequestBase.WriteBodyToXml (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:429:14)         
    at CreateResponseObjectRequest.ServiceRequestBase.WriteToXml (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:497:14)             
    at CreateResponseObjectRequest.ServiceRequestBase.EmitRequest (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:164:18)            
    at CreateResponseObjectRequest.ServiceRequestBase.BuildXHR (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:130:14)               
    at /home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:42:33                                                                    
    at new Promise (/home/atikri/workspacenode/old/test-ews/node_modules/winjs-node/src/js/WinJS/Promise/_StateMachine.js:988:13)                                                                    
    at WinJSPromiseApi.create (/home/atikri/workspacenode/old/test-ews/node_modules/ews-javascript-api/js/Promise_WinJS.js:12:16)   
````

**Comment by gautamsi** [comment]
what is the version you are using?

**Comment by alitriki** [comment]
I just re-did **npm install ews-javascript-api** an hour ago, so the last version I guess.

**Comment by gautamsi** [comment]
will be fixed in next npm publish, you can fix it yourself for now by adding missing line in `CancelMeetingMessageSchema.js`

```js
    CancelMeetingMessageSchema.Instance = new CancelMeetingMessageSchema(); //missing line
    return CancelMeetingMessageSchema; // existing line, should be line 38
```

**Comment by gautamsi** [comment]
just pushed 0.7.1 to fix this issue

**Comment by alitriki** [comment]
I just Updated to 0.7.1 and it works ! 
Thanks  :smiley:
